// This file is automatically generated from your CSS. Any edits will be overwritten.
export const container: string;
export const header: string;
export const main: string;
export const footer: string;
