// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
  export interface IStyleCss {
    collapsing: string;
    component: string;
    "component-content": string;
    "component-detail": string;
    "component-detail-wrapper": string;
    "component-header": string;
    "copy-button": string;
    "expand-button": string;
    expanding: string;
    expansion: string;
    type: string;
    value: string;
  }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
