// This file is automatically generated from your CSS. Any edits will be overwritten.
export const component: string;
export const componentHeader: string;
export const type: string;
export const value: string;
export const copyButton: string;
export const componentContent: string;
export const componentDetail: string;
export const collapsing: string;
export const expansion: string;
export const expanding: string;
export const componentDetailWrapper: string;
export const expandButton: string;
