// This file is automatically generated from your CSS. Any edits will be overwritten.
export const checkboxes: string;
export const entry: string;
export const entryInput: string;
export const removeButton: string;
export const appendButton: string;
