// This file is automatically generated from your CSS. Any edits will be overwritten.
export const container: string;
export const box: string;
export const visitButton: string;
export const visitLink: string;
export const copyButton: string;
