// This file is automatically generated from your CSS. Any edits will be overwritten.
export const entry: string;
export const key: string;
export const value: string;
export const removeButton: string;
export const appendButton: string;
